cyberdolphin:
  openai_compatible:
    default:
      api_base: "http://url:3200/v1"
      organisation: "NONE"
      api_key: "sk-xxxxxxx"
      model: 
        - "your_model_here"
        - "glm-4"
        - "chatglm_pro"
        - "ERNIE-Bot-4"
        - "qwen-turbo-internet"
        - "gpt-3.5-turbo"
        - "gpt-3.5-turbo-16k"
        - "gpt-3.5-turbo-16k-0613"
        - "gpt-4-0613"
        - "gpt-4-1106-preview"
      vison_key_ali: "sk-xxxxx"  
      vision_model_ali: 
        - "your_model_here"
        - "qwen-vl-plus"
        - "qwen-vl-max"
      vison_key_gemini: "AIxxxxxx"
      vision_model_gemini: 
        - "your_model_here"
        - "gemini-pro-vision"
      vison_key_GLM4: "xxxxxx"
      vision_model_GLM4: 
        - "your_model_here"
        - "glm-4v"
        - "glm-4"


  example_user_prompt: "your user prompt here"
  prompt_templates:
#    the user prompt is by default a list of objects, such as what might be returned from a resnet node

    default:
      system: >-
        act as prompt generator ,i will give you text and you describe an image that match that text in details, answer with one response only.I input in Chinese to communicate with you, but it is crucial that your response be in English.
      prefix: >-
        make a list of the things you see. do not explain why you see them.
        do explain what the things you see are doing. do explain where they are.
        do not explain their purpose,
        do not say anything other than the list of things you see.
        do use purely objective language: do not say "I see a..." but instead say "there is a..."
        SO:
        When I provide the list "
      suffix: >-
        ",
        what is this scene -
        do not simply repeat the list, do not say "when I provide the list" or similar just project the description.
        describe what you see in your mind.
    

    prompt_two_example:
      system: >-
        You are deeply artistic, understanding of concepts like composition, palette and color theory, and image psychology.
      prefix: >-
        describe a scene using the following list of objects: "
      suffix: >-
        " - there are many things
        and you must list them using a maximum of 25 words. be clear and specific.
        use present tense, objective language: do not say, "I see ..." rather say, "there is ..."
    

    gpt-3.5-turbo:
      system: >-
        You are deeply artistic, understanding of concepts like composition, palette and color theory, and image psychology.
      prefix: >-
        describe a scene using the following list of objects: "
      suffix: >-
        " - there are many things
        and you must list them using a maximum of 25 words. be clear and specific.
        use present tense, objective language: do not say, "I see ..." rather say, "there is ..."
    
